### ISSUE TITLE
agent try to join mesh, but the save button is disable

### ISSUE THREAD

**Issue by wujian0327** [flomesh-io/ztm#2]
The test environment is as follows：
Ubuntu 22.04
pipy version:
![image](https://github.com/flomesh-io/ztm/assets/125539882/72c9851a-0045-44d2-a5b3-ca94186a4e19)

Operating procedures：
1. Clone the pipy and ztm.
2. Install pipy.
3. Intall ztm gui.
4. Start the ca, hub and agent respectively according to the README.md.
5. Open the agent website and try to join mesh.
6. Cannot click the save button.
![image](https://github.com/flomesh-io/ztm/assets/125539882/406887c3-2f43-4f50-ba82-e3aa6964e168)

**Comment by keveinliu** [comment]
Hi,

Thanks for your update.
It's an UI issue. Once you entered the Hub's address, you need to press 'Enter' key to finishing the input.
Sorry for bothering.
Enjoy it!

Cheers!

**Comment by wujian0327** [comment]
thanks
