### ISSUE TITLE
mac 访问 127.0.01:7777，左侧菜单没有 apps

### ISSUE THREAD

**Issue by gray0128** [flomesh-io/ztm#40]
mac安装ztm-app-v0.1.0-macos-arm64.dmg，访问 127.0.01:7777，左侧菜单没有 apps。
但使用http://127.0.0.1:7777/#/mesh/apps 可以正常打开

**Comment by keveinliu** [comment]
@gray0128 Hi，
请问是否解决了你的问题？
谢谢~

**Comment by gray0128** [comment]
> @gray0128 Hi， 请问是否解决了你的问题？ 谢谢~

没有，我是要管理 tunnel，app 菜单入口里边并没有，目前只能用 http://127.0.0.1:7777/#/mesh/apps 进

**Comment by gray0128** [comment]
> @gray0128 Hi， 请问是否解决了你的问题？ 谢谢~

莫名其妙，我试图用 0.2.0版本，但不太会操作。结果现在进入 apps后有tunnel 了
