### ISSUE TITLE
0.2.0版本在 macos 上点击 join 无反应

### ISSUE THREAD

**Issue by gray0128** [flomesh-io/ztm#43]
0.2.0版本在 macos 上点击 join 无反应，无法加入新的 hub。
无论是 app，还是用浏览器访问 7777 都不行

**Comment by keveinliu** [comment]
我这里没办法重现你问题，麻烦重新下载再试一下？
如果还有问题，麻烦看一下ztm-app的MD5，以及MacOS版本是什么？

**Comment by gray0128** [comment]
> 我这里没办法重现你问题，麻烦重新下载再试一下？ 如果还有问题，麻烦看一下ztm-app的MD5，以及MacOS版本是什么？

macOS Sonoma 14.6.1
MD5:85a61f2cba2727e37acd8fbc3b268af7
我不确认我查看 md5的方法是否正确：md5 /Applications/ztm.app/Contents/MacOS/ztm
<img width="730" alt="image" src="https://github.com/user-attachments/assets/b28b3197-3b36-4630-ad9f-78aa7c80a5b0">

**Comment by caishu97** [comment]
Try new release 0.3, please. It works now.
