### ISSUE TITLE
关于windows使用体验

### ISSUE THREAD

**Issue by yafoo** [flomesh-io/ztm#47]
我想用这个软件，但是到现在没有搭建成功。

我的需求是：我windows电脑有公网ip，而且24小时不关机。所以，想在windows电脑上部署hub，然后在这台电脑上在部署一个ep，然后在手机和其他电脑上部署ep，实现电脑和手机之间连接。

现在的问题是windows版的hub没法直接启动运行，同时再启动windows版的ep好像也有问题，会和hub有冲突。

希望能提供提供一个exe hub，点击就可以直接运行了。如果这个hub能包含ep的功能，不用在这台电脑上再安装ep最好了。

**Comment by keveinliu** [comment]
你好，
作为Hub，需要一个条件：所有的Agent都可以连通这个Hub。请问你的Windows电脑是否有公网IP？
一般来说，针对你的场景，应该有一个有公网IP的主机（例如一个公有云主机）。
请从Release页面中下载 [ztm-aio-v0.3.0-win-x86_64.tar](https://github.com/flomesh-io/ztm/releases/download/v0.3.0/ztm-aio-v0.3.0-win-x86_64.tar)。
运行命令跟在Linux上一致。（https://github.com/flomesh-io/ztm/wiki/5.-HOWTO-:-Start---stop-ztm-hub-and-agent）
谢谢！

**Comment by yafoo** [comment]
有公网ip的。运行，提示不支持此平台

**Comment by keveinliu** [comment]
我刚在Windows 11上测试过，可以运行的。麻烦把运行错误和系统信息都截个图？

**Comment by yafoo** [comment]
好的，明天吧。我的是win10

**Comment by yafoo** [comment]
![image](https://github.com/user-attachments/assets/aab9a64c-df56-49e4-a722-30faca027cf8)

**Comment by keveinliu** [comment]
你好，

ztm start使用的是Linux systemd服务，所以不支持Windows。目前Windows只能用ztm run，后面的参数一样。
ztm run就是在前台跑，不要关闭PowerShell窗口。

**Comment by yafoo** [comment]
> 你好，
> 
> ztm start使用的是Linux systemd服务，所以不支持Windows。目前Windows只能用ztm run，后面的参数一样。 ztm run就是在前台跑，不要关闭PowerShell窗口。

前台跑，难以接受啊。主要我这电脑经常会无故重启，看看能不能优化windows上运行。

**Comment by keveinliu** [comment]
近期没有计划在Windows上推出ztm hub服务，你可以尝试使用docker跑一个后台。
HUB的地址是：flomesh/ztm-hub:0.3.0

**Comment by yafoo** [comment]
好的，之前没看到这个docker 镜像。自己用docker拉的一些环境，也是跑不起来hub
