### ISSUE TITLE
wiki guide bug:  ZTMesh client: Only available for the MacBook architecture, not available for the x86 architecture.

### ISSUE THREAD

**Issue by xiaods** [flomesh-io/ztm#5]
<img width="658" alt="截屏2024-05-11 上午12 14 07" src="https://github.com/flomesh-io/ztm/assets/37678/411eb390-10c4-4700-996b-718578891264">

1. The tutorial on the wiki cannot proceed as there is a lack of verification for some key steps, making it difficult to work out. It is suggested to optimize it into 2 nodes, with the server serving as an example, which can fully act as two roles, hub and megatron.
2. the prepare section on wiki contains useless git clone step. suggest remove the useless info.

**Comment by keveinliu** [comment]
Thanks for your points!
1. Since this wiki is about how to access your home nodes, so I run three nodes. We'll demonstrate its concept and  network topology in README, to make it clear to users.
2. Indeed we haven't prepare so well in v0.0.1. I'll update the wiki after v0.0.2 released, will be soon in a week.

Thank you very much!
Cheers!

**Comment by keveinliu** [comment]
Update:
1. Wiki has been updated. Also README in ztm repo has been updated.
2. ZTMesh v0.0.2 has MacOS(arm64/x64) and Windows(x64). In next release, we'll provide more artifacts of Linux and mobile.

**Comment by xiaods** [comment]
> Update:
> 
> 1. Wiki has been updated. Also README in ztm repo has been updated.
> 2. ZTMesh v0.0.2 has MacOS(arm64/x64) and Windows(x64). In next release, we'll provide more artifacts of Linux and mobile.

I will double check later. thanks

**Comment by xiaods** [comment]
hi, came across another issue on client side and there is confuse for me.

![Image_20240513222251](https://github.com/flomesh-io/ztm/assets/37678/dccc53ae-72f6-41fb-b02c-d28e36f2f8ea)

I am not sure wether i need do all cli step and graph ui step together?  my environment is two server:
* aws server, setting role is ztm hub and backend server.
* my local mac, as client server, don't know what step should be do step by step.

**Comment by keveinliu** [comment]
> hi, came across another issue on client side and there is confuse for me.
> 
> ![Image_20240513222251](https://private-user-images.githubusercontent.com/37678/330093860-dccc53ae-72f6-41fb-b02c-d28e36f2f8ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MTM3MjMsIm5iZiI6MTcxNTYxMzQyMywicGF0aCI6Ii8zNzY3OC8zMzAwOTM4NjAtZGNjYzUzYWUtNzJmNi00MWZiLWIwMmMtZDI4ZTM2ZjJmOGVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDE1MTcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5OGVmNTU5MDIyMzhjMzMyMGFjMjliZGVhM2VjYjQ1MzA2YmYxZWQ5NmIyMTJhYmU0ZDVlOGM1M2E3ODgwOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aY-Km47MnqwTPZL26chUo878kpQo8Hq_RNtkaxeCFpQ)
> 
---> Seems pipy didn't start correctly, so you can't configure mesh.

> I am not sure wether i need do all cli step and graph ui step together? my environment is two server:
---> In "Join the mesh" section of wiki, I provide two different examples by using cli and gui. Cli is for servers which don't have desktop, and gui is for desktop OS(like MacOS or Windows). In fact, you can run a ztm agent by cli or gui. It both works.

> * aws server, setting role is ztm hub and backend server.
-----> Run CA server, Hub, "Join the mesh by Cli". All steps in command line.
> * my local mac, as client server, don't know what step should be do step by step.
----> Both cli and gui work. I recommend GUI. And it's better to use GUI as mesh admin.

Hope I've answered your questions. Feel from to drop further questions here.
Cheers!

**Comment by xiaods** [comment]
> > hi, came across another issue on client side and there is confuse for me.
> > ![Image_20240513222251](https://private-user-images.githubusercontent.com/37678/330093860-dccc53ae-72f6-41fb-b02c-d28e36f2f8ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MTM3MjMsIm5iZiI6MTcxNTYxMzQyMywicGF0aCI6Ii8zNzY3OC8zMzAwOTM4NjAtZGNjYzUzYWUtNzJmNi00MWZiLWIwMmMtZDI4ZTM2ZjJmOGVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDE1MTcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5OGVmNTU5MDIyMzhjMzMyMGFjMjliZGVhM2VjYjQ1MzA2YmYxZWQ5NmIyMTJhYmU0ZDVlOGM1M2E3ODgwOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aY-Km47MnqwTPZL26chUo878kpQo8Hq_RNtkaxeCFpQ)
> 
> ---> Seems pipy didn't start correctly, so you can't configure mesh.
> 
> > I am not sure wether i need do all cli step and graph ui step together? my environment is two server:
> 
> ---> In "Join the mesh" section of wiki, I provide two different examples by using cli and gui. Cli is for servers which don't have desktop, and gui is for desktop OS(like MacOS or Windows). In fact, you can run a ztm agent by cli or gui. It both works.
> 
> > * aws server, setting role is ztm hub and backend server.
> 
> -----> Run CA server, Hub, "Join the mesh by Cli". All steps in command line.
> 
> > * my local mac, as client server, don't know what step should be do step by step.
> 
> ----> Both cli and gui work. I recommend GUI. And it's better to use GUI as mesh admin.
> 
> Hope I've answered your questions. Feel from to drop further questions here. Cheers!

thanks, let me double check again

**Comment by xiaods** [comment]
@keveinliu I already double check my environment with ZTM and pipy.

<img width="860" alt="截屏2024-05-14 下午9 58 15" src="https://github.com/flomesh-io/ztm/assets/37678/7d8f87ba-ea7a-417a-8daf-a13fdbb5ecde">

because the pipy is not working on MacOS Intel version. the pipy link is come from here: [pipy-ztm-v0.0.2-macos-x64.zip](https://github.com/flomesh-io/ztm/releases/download/v0.0.2/pipy-ztm-v0.0.2-macos-x64.zip)

the pipy issue also caused the ZTM graph app is not working on my environment. please double check. thanks a lot.

**Comment by xiaods** [comment]
After repeatedly reading the tutorial, I believe that there are many redundant steps in the current tutorial. Some steps do not clearly state the commands, which leads to the need for alignment of content and causes confusion for novice users. I think that the scenario plan should be one-click through to the end, without interrupting novice users. A tutorial that allows users to follow step by step and achieve success is what is needed. The current tutorial cannot achieve this. Based on the current situation, I suggest that you revise it using large model services such as ChatGPT. There are also many English descriptions that are not clear to understand. Please use ChatGPT4o to help you correct them. It will only take a few seconds. Thank you.

**Comment by xiaods** [comment]
![Image_20240515103225](https://github.com/flomesh-io/ztm/assets/37678/39b29d3e-bc75-4a37-9c30-bc80a7fd71a8)
I am also confuse why came across this issue. please help me

**Comment by xiaods** [comment]
another case: in windows 10 env:
1. download graph app:  ZTMesh_v0.0.2_win_x64.msi and install.
2. follow wiki guide: https://github.com/flomesh-io/ztm/wiki/HOWTO:-How-to-access-my-home-Linux-from-office-macOS-by-ztm%3F#with-graphical-ui , the start button is not working for me.

![Image_20240515104120](https://github.com/flomesh-io/ztm/assets/37678/24105ac6-24cc-4522-81c6-efeba225c6a2)

**Comment by xiaods** [comment]
with my dig info. it works like a charm.

Conclusion: ztm need pipy engine. so through the wiki guide, only the below cmd is valid:
```
$ arch=`uname -m`
$ wget https://pipy-oss-1255617643.cos-website.ap-beijing.myqcloud.com/repo/pipy/${arch}/binary/pipy-1.1.0-33-generic_linux-${arch}.tar.gz
$ tar xvf pipy-1.1.0-33-generic_linux-${arch}.tar.gz && sudo cp -f usr/local/bin/pipy /usr/local/bin && rm -fr usr
```
and the ztm project's release page attach all invalid packag.
https://github.com/flomesh-io/ztm/releases/tag/v0.0.2
i have also check the status:
1. [pipy-ztm-v0.0.2-macos-x64.zip](https://github.com/flomesh-io/ztm/releases/download/v0.0.2/pipy-ztm-v0.0.2-macos-x64.zip)  is not working
2. [pipy-ztm-v0.0.2-ubuntu-x64.gz](https://github.com/flomesh-io/ztm/releases/download/v0.0.2/pipy-ztm-v0.0.2-ubuntu-x64.gz) is not working
3. [pipy-ztm-v0.0.2-windows.zip](https://github.com/flomesh-io/ztm/releases/download/v0.0.2/pipy-ztm-v0.0.2-windows.zip) is not working
4. [ZTMesh_v0.0.2_macos_x64.dmg](https://github.com/flomesh-io/ztm/releases/download/v0.0.2/ZTMesh_v0.0.2_macos_x64.dmg) is not working
5. [ZTMesh_v0.0.2_win_x64.msi](https://github.com/flomesh-io/ztm/releases/download/v0.0.2/ZTMesh_v0.0.2_win_x64.msi) is not working

I finally succeeded by browsing the design principles of ZTM on the wiki and using the ZTM source code repository to make the call.

![Image_20240515105952](https://github.com/flomesh-io/ztm/assets/37678/5d4c30df-fbed-401e-b114-9660ae9c7832)
